# rm unsupported modes on macs, like host n/w mode
version: '2.1'
services:
  pyspark-nb:
    image: sotera/pyspark-mongo-jupyter:2
    ports:
      - "8888:8888"
    environment:
      - GRANT_SUDO=yes
      - TINI_SUBREAPER=true
      # Note: PYTHONPATH overwritten to include mounted dirs. better way to expose packages to workers?
      - PYTHONPATH=/usr/local/spark/python:/usr/local/spark/python/lib/py4j-0.10.4-src.zip:/home/jovyan/work/util:/home/jovyan/work/app
    volumes:
      # application files
      - $PWD/app:/home/jovyan/work/app
      # copy data files here (git ignored)
      - $PWD/data:/home/jovyan/work/data
      # notebooks
      - $PWD/nb:/home/jovyan/work/nb
      # util files
      - $PWD/../../../services/util:/home/jovyan/work/util
