version: '2.1'

# runs jupyter on localhost:8888 by default.
# can run in either spark local or standalone cluster mode.
# i.e.
  # SparkSession.builder.master("spark://master:7077").getOrCreate()
  # SparkSession.builder.master("local[*]").getOrCreate()

# in either mode, localhost:4040 is the Spark app UI.
# in cluster mode, localhost:9090 is the master UI.

networks:
  watchman:
    # connect to existing watchman network
    external:
      name: compose_default

services:
  pyspark-nb:
    networks:
      - watchman
    image: sotera/pyspark-mongo-jupyter:4
    ports:
      - "4040:4040"
      - "8080:8080"
      - "8888:8888"
    environment:
      GRANT_SUDO: "yes"
    extends:
      file: common.notebook.yml
      service: pyspark

  master:
    networks:
      - watchman
    image: sotera/pyspark-mongo-jupyter:4
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
      SPARK_EXECUTOR_MEMORY: 6g
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - "5050:4040"
      - "6066:6066"
      - "7077:7077"
      - "9090:8080"
    extends:
      file: common.notebook.yml
      service: pyspark

  worker:
    networks:
      - watchman
    image: sotera/pyspark-mongo-jupyter:4
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 8
      SPARK_WORKER_MEMORY: 6g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - "8081:8081"
    depends_on:
      - master
    extends:
      file: common.notebook.yml
      service: pyspark
